### PR TITLE
made it more vibrant and kept it simple #2

### PR DESCRIPTION
**Pull request by AADESHak007**
So I was only able to change the UI of the website a bit . I tried for changing the toggle theme but wasnt able to it as it was getting messy so left it  . 
Any ways here is the first look  of the website for you ...
Screenshot 2024-10-05 102512

### CODE REVIEW

**Review by pranjalee30 — CHANGES_REQUESTED** [review]
Its looking good but if you change the theme for the website you have to change from all wherever it applicable, I meant that about page is still from previous theme and the main is toggling the theme its necessary if you change this.

go to the codebase and review the  codes you definately get the idea how to do it i will merge it after you completed it.

I liked the video you added keep the height somewhat small.   

All the best 👍

**Comment by AADESHak007** [comment]
I tried doing working on the toggle theme button mode but I was stuck .. I 'll give it another go  . Just give me time till Sunday 2 pm.

**Comment by pranjalee30** [comment]
> I tried doing working on the toggle theme button mode but I was stuck .. I 'll give it another go . Just give me time till Sunday 2 pm.

ok no issue, take your time you can do it

**Comment by AADESHak007** [comment]
pulled the changes with new branch for issue#2

**Pull request closed without merging**
