### PR TITLE
updated cakes.json

### PR DESCRIPTION
**Pull request by Abhiraj-Sardar**
hi @pranjalee30 ,

I just added some more data in the cakes.json file, now the file contains 30 cakes info.

### CODE REVIEW

**Review by pranjalee30 — CHANGES_REQUESTED** [review]
Its good but the cake image is of different size so fix this also then i will merge your request

**Comment by Abhiraj-Sardar** [comment]
> Its good but the cake image is of different size so fix this also then i will merge your request

ok 👍

**Comment by Abhiraj-Sardar** [comment]
hi @pranjalee30 ,

I updated my previous code. ensuring the image size is the same for all.
Thanks for your thorough review.

**Review by pranjalee30 — COMMENTED** [review]
Good Work 👍. if you want to add more enhacement, you are welcome

**Comment by Abhiraj-Sardar** [comment]
> Good Work 👍. if you want to add more enhacement, you are welcome

Sure 👍

**Pull request merged**
